### ISSUE TITLE
remove `outline` when using bootstrap

### ISSUE THREAD

**Issue by jerrybendy** [jaywcjlove/magic-input#1]
hi man, when I use magic input with bootstrap, checkbox and radio button will cover a outline shadow when the element active. Bootstrap default define a `outline` style for form control active status, 

![image](https://cloud.githubusercontent.com/assets/7897384/14980458/58750074-115b-11e6-91da-3be9241e6152.png)

Easy way to resolve it is remove the `outline` style from bootstrap

``` css
outline: none;
```

Thanks

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/magic-input/blob/master/lib/mixins.styl#L30

remove `outline` ?    This is not beautiful enough.  

When activated, I gave an effect.

``` css
.mgc:focus {
    outline: none;
    box-shadow: inset 0 1px 1px rgba(255,255,255,0.075),0 0 2px #38a7ff;
}
```

**Comment by jerrybendy** [comment]
I'm sorry for my mistake.

I have inspect the elements, and get the original reason which bootstrap's style has overwrite magic-input, even I make bootstrap code before magic-input.

![image](https://cloud.githubusercontent.com/assets/7897384/14982072/1713d866-1166-11e6-9e33-d1bebe7421e3.png)

If I change the code like that, it can work well:

``` css
input[type="radio"].mgr:focus,
input[type="checkbox"].mgc:focus {
    outline: none;
    box-shadow: inset 0 1px 1px rgba(255,255,255,0.075), 0 0 2px #38a7ff;
}
```

Sorry for my poor English, hope you can understand what I said.  :grin:

**Comment by jaywcjlove** [comment]
@jerrybendy My me too.My English is very bad.  😄

**Comment by jerrybendy** [comment]
也是醉了，早说你会中文，害我乱敲了半天英语 😅

关于样式优先级级问题，`.mgr`和`.mgc`的样式会被bootstrap的样式覆盖的问题，还有什么好的解决方案吗？ 目前发现的只要在 `:focus`上面加上属性限制就可以正常使用，其它部分样式没有具体测试会不会被覆盖掉

**Comment by jaywcjlove** [comment]
`.mgr`和`.mgc` 哪些样式被覆盖了呢？`bootstrap` 不太用...

英语交流学习英语 (^O^)

**Comment by jerrybendy** [comment]
看我昨天回复中的截图，bootstrap中有个`input[type="radio"]:focus`的样式，根据CSS的覆盖规则，bootstrap中比较详细的匹配自然会覆盖掉 magic-input 中仅有类名的匹配，而在 magic-input 中如果添加了 `input[type="radio"]`这样的属性限制就会拥有和 bootstrap 中相同的优先级，就会使用后面的代码覆盖前面代码的简单规则。

所以下面这种写法是可行的

``` css
input[type="radio"].mgr:focus,
input[type="checkbox"].mgc:focus {
    outline: none;
    box-shadow: inset 0 1px 1px rgba(255,255,255,0.075), 0 0 2px #38a7ff;
}
```

目前我使用中已知的会被覆盖掉的部分只有`fource`，但不排除没有其它地方有冲突，或者与其它框架之间是否有冲突。如果是在所有的`.mgr`中都加上约束会使文件变得更大，但兼容性会更好。

以上都是用`radio`举例，`checkbox`相同
